services:
  cron:
    image: ghcr.io/wikiteq/cron
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/cron:/var/log/cron
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - DEBUG=${CRON_DEBUG:-0}
    labels:
      # Enable cron scheduling for the cron container itself
      - cron.enabled=true
      # Log archiving job - runs monthly and creates archives when a period accumulates 100 files
      - cron.rotate_cron_logs.schedule=@monthly
      - cron.rotate_cron_logs.command=archive-cron-logs 100

  app:
    build: ./app
    container_name: app
    labels:
      # Enable cron scheduling for this container
      - cron.enabled=true
      # Example cron jobs
      - cron.mytask.schedule=* * * * *
      - cron.mytask.command=/usr/local/bin/app_script.sh
      - cron.another_task.schedule=*/2 * * * *
      - cron.another_task.command=/usr/local/bin/another_app_script.sh
